language: node_js
node_js:
- '8'
cache: yarn
env:
  global:
    secure: ZoPSwd7azOzLRhBPV6nt5qwOlEReVuYwERBHPv48iaXzQPxjx4sz53YP/TuLZ/3dnRlcBCujL6JJvDYZ+0VQ2LbOcwyvCJia6kc52p8loYMTVl9grp47nHfOBE2qVFxHU9J61kWvq3AQ4qjHaQNU/XYc8I2NPWI8c5DGrY5j3iOrXOr12/bKERYzWNY4D/2FlDvfQ8Bzcdav2jH+THgxeuorIVgq2/6jUVyHvcQ7BYiYN5rSzZBMsZJNcZWPiFLi6qKLJwsCRQ8dLHpx5lOzGOl1nqp+MRDJV9893QiwUy1ku9xQcbCsDY6H0HuLnoWIL6Y37i3FGCRwWKP+xuWuv7Xeeo0jt6gMfZzZsngsIPVwuCN/6GYpnBPcdDqp4Ws32BXy19byeWjzidmYt4tA94JR/IGYIb4hfnjJe0Z3dkZzj0xfys6pkHzTeuOBIg/prwO2AT+49R34X5LzVVsTcjCRWqj7mfJDel79WFjRHO2SKIHWxyrMz1Z7jFUBFy02nZIO4ZBQFqB9ioDQi2VnTpZXnfJ7xXOl9SoL4TShqelnQ7kssfmqerepuu72azCXli8mSB5rHeLY+LA4p2jYV2eVdJfMJgORkB+RliyxiUzsacL0ZcmycUC7hIPR/50m9OBr/1qmkK93P4X7tYn1H85us9u5SjEVG2L6gMwY05Y=
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm run ci
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  skip_cleanup: true
  email: rplan-ci@actano.de
  api_key:
    secure: eeL8p4+42G4m3QwLJlviuI+iX3K+ip3P1++G+rR3KakfF5udl0uIuwHolcHXo9t7qT/q5cbCxuJS1MCw8ehWel1w60W8ffOXL28M/lEoDwU0wEkLLfErWpdhZUsoAv4ERFkKlzQAOWHH06UNJQ1MNrgEYIgzHww2TlrWfo+Bxrvn5QRVbcyEtpEVWPhV0SrDht9tbNuQ3utdi0kpEtI1S+fxXNS3tVHteQoLZDvA49dBfb3LTU9JWSOAv+atsAsF3UzAg3OAwcI/SL3Ez48abEs/ZrVXa4J8Ykpihg766f0yjgqBR1fQOhAxVgKj5tlDEaaXSLNSYqMXqj7Hy/nQ5wiK46KrjBUp6IicxVa2+/cLuDA3Up6y7o3qee95qPrz4bg0MxOZazCBxEMAxERy3SmX3NCrow5CP3DiAv3Oy7X0Kp2tb4NgqOBmZqc2IPwP+wuxtodPwaM3maKkedfT7fDgGWJpUJzsNJay6etUprba/vxBYI5uXHUYXwbuirYWyTe5lpmxrsmkBXxwTnC+GacgYVh/0QQ32FgF1DxGSsMLiJywYnSFGAQnX9Gt5fz0Zw+9l3VfGQo0hlclfoK9WjWTQJ1vpI2hSAkkWYyogda81eMKn/FifH9EIQox7T6x5VV/QRez1bn8ITi2fng+oGKgXWdSyn+MlmuNYBSgwD8=
  on:
    tags: true
    repo: actano/borders-logging
    node: '8'
